version: "3.2"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "50051:50051"
    networks:
      - generalnet
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app
    networks:
      - generalnet
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8080:8080"
  #   # volumes:
  #   #   - ./frontend:/app
  #   networks:
  #     - generalnet
  #   depends_on:
  #     - backend
  grpc-client:
    build:
      context: ./grpc_client
      dockerfile: ./Dockerfile
    volumes:
      - ./grpc_client:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./net/data:/app/data
    depends_on:
      - api
      - backend
    networks:
      - generalnet
    environment:
      - PYTHONUNBUFFERED=1

networks:
  generalnet:
