version: "2.1"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "50051:50051"
#   python:
#     build:
#       context: ./client
#       dockerfile: ./Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./client:/usr/src/client
#     links:
#       - backend
