version: "3.2"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "50051:50051"
    networks:
      - mynet
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    networks:
      - mynet
  grpc-client:
    build:
      context: ./grpc_client
      dockerfile: ./Dockerfile
    volumes:
      - ./grpc_client:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    depends_on:
      - api
      - backend
    networks:
      - mynet

networks:
  mynet:


