version: "2.1"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "50051:50051"
  python:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
